# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build and push an image
      inputs:
        containerRegistry: 'dockerRegistry'
        repository: 'haythembahri/mvc-app'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        #tags: '$(tag)'
        tags: 'v2.$(Build.BuildId)'
    # - task: CopyFiles@2
    #   displayName: copy
    #   inputs:
    #     Contents: |
    #       mssql-config-map.yaml
    #       mssql-pv.yaml
    #       mssql-secret.yaml
    #       products-store-mssql-deployment.yaml
    #       products-store-mvc-deployment.yaml
    #     TargetFolder: '$(Build.ArtifactStagingDirectory)'
    # - task: PublishBuildArtifacts@1
    #   inputs:
    #     PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    #     ArtifactName: 'drop'
    #     publishLocation: 'Container'
        
