# We need the the StorageClass object only when we provision
# the hardware resources (creation of Azure Disk in this case)
# to run the app.
# The Disk should be created at first,
# this could be done even manually, with no automation.
# If we want to automate this, then we should do this
# using Infrastructure as Code (IaC)
# (i.e Terraform, Cloud Formation, ARM templates).
# The CD pipeline should worry more on the repetitve tasks.

kind: PersistentVolume
apiVersion: v1
metadata:
  name: mssql-persistent-volume
  namespace: {{ .Values.namespace }}
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mssql-pv-claim
  namespace: {{ .Values.namespace }}
#  annotations:
#    volume.beta.kubernetes.io/storage-class: azure-disk-1gb-{{ .Values.buildId }}
spec:
  # storageClassName: default
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
